set lines=40
set columns=120
set showtabline=2
set transparency=30
set guioptions-=T

colorscheme desert

"全角スペースを視覚化
highlight ZenkakuSpace cterm=underline ctermfg=darkgray gui=underline guifg=LightBlue guibg=gray30
au BufNewFile,BufRead * match ZenkakuSpace /　/

