" OS
let s:is_win   = has('win32') || has('win64')
let s:is_mac   = has('mac') || system('uname') =~? '^darwin'
let s:is_linux = !s:is_mac && has('unix')

filetype plugin indent on " Required for Neobundle

if has('vim_starting')
  set nocompatible               " Be iMproved
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
NeoBundleFetch 'Shougo/neobundle.vim'

" Recommended to install
NeoBundle 'Shougo/vimproc.vim', {
      \ 'build' : {
      \     'windows' : 'tools\\update-dll-mingw',
      \     'cygwin' : 'make -f make_cygwin.mak',
      \     'mac' : 'make -f make_mac.mak',
      \     'unix' : 'make -f make_unix.mak',
      \    },
      \ }

" My Bundles here:
NeoBundle 'L9'
NeoBundle 'FuzzyFinder'

NeoBundle 'vim-ruby/vim-ruby'
NeoBundle 'vim-jp/cpp-vim'
NeoBundle 'tpope/vim-rails'
NeoBundle 'tpope/vim-bundler'
NeoBundle 'alpaca-tc/neorspec.vim'
NeoBundle 'ngmy/vim-rubocop'
NeoBundle 'tpope/vim-rbenv'
NeoBundle 'Rip-Rip/clang_complete'
NeoBundle 'xolox/vim-misc'
NeoBundle 'xolox/vim-lua-ftplugin'
NeoBundle 'xolox/vim-lua-inspect'
NeoBundle 'jnwhiteh/vim-golang'
NeoBundle 'pangloss/vim-javascript'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'mattn/webapi-vim'
NeoBundle 'AtsushiM/sass-compile.vim'
NeoBundle 'gregsexton/gitv'
NeoBundle 'kana/vim-fakeclip'
NeoBundle 'surround.vim'
NeoBundle 'matchit.zip'
NeoBundle 'vim-jp/vital.vim'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'mattn/emmet-vim'
NeoBundle 'tpope/vim-endwise'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'rstacruz/sparkup', {'rtp': 'vim/'}
NeoBundle 'elzr/vim-json'
NeoBundle 'osyo-manga/vim-over'
NeoBundle 'LeafCage/yankround.vim'
NeoBundle 'h1mesuke/vim-alignta'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'itspriddle/vim-marked'
NeoBundle 'tpope/vim-markdown'
NeoBundle 'thinca/vim-quickrun'
NeoBundle 'tpope/vim-dispatch'
NeoBundle 'szw/vim-tags'                              "Ctags generator
NeoBundle 'rcyrus/snipmate-snippets-rubymotion'
NeoBundle 'groovyindent'
NeoBundle 'tfnico/vim-gradle'
NeoBundle 'xuhdev/indent-java.vim'
NeoBundle 'tpope/vim-classpath'

NeoBundle 'hail2u/vim-css3-syntax', {
      \ 'autoload' : {
      \   'filetypes' : ['css']
      \ }
      \}

NeoBundleLazy 'scrooloose/syntastic', {
      \ 'autoload' : {
      \   'commands' : ['SyntasticCheck']
      \ }
      \}

NeoBundleLazy 'alpaca-tc/alpaca_tags', {
      \ 'depends': ['Shougo/vimproc'],
      \ 'autoload' : {
      \   'commands' : [
      \     { 'name' : 'AlpacaTagsBundle', 'complete': 'customlist,alpaca_tags#complete_source' },
      \     { 'name' : 'AlpacaTagsUpdate', 'complete': 'customlist,alpaca_tags#complete_source' },
      \     'AlpacaTagsSet', 'AlpacaTagsCleanCache', 'AlpacaTagsEnable', 'AlpacaTagsDisable', 'AlpacaTagsKillProcess', 'AlpacaTagsProcessStatus',
      \ ],
      \ }}

" if_luaが有効ならneocompleteを使う
NeoBundle has('lua') ? 'Shougo/neocomplete' : 'Shougo/neocomplcache'

" Unite and plugins
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neomru.vim'
NeoBundle 'ujihisa/unite-colorscheme'
NeoBundle 'h1mesuke/unite-outline'

" vimrc Benchmark
NeoBundle 'mattn/benchvimrc-vim'

" Color schemes
"" molokai only!
NeoBundle 'tomasr/molokai'

" TextObject
NeoBundle 'kana/vim-textobj-user'
NeoBundle 'nelstrom/vim-textobj-rubyblock'      " rr:all blocks, ro:definitions, rl:loop, rc:control, rd:do for ruby blocks
NeoBundle 'deris/vim-textobj-enclosedsyntax'    " aq, iq for treat enclosed syntax
NeoBundle 'kana/vim-textobj-indent'             " al, il for indent block
NeoBundle 'mattn/vim-textobj-url'               " au, iu for url
"NeoBundle 'mjbrownie/html-textobjects'          " Html textobject
NeoBundle 'osyo-manga/vim-textobj-multiblock'   " Unite (, [, { to ab, ib, and multiple block
NeoBundle 'osyo-manga/vim-textobj-multitextobj' " To gather multiple textobject into one textobject

" misc
NeoBundle 'deris/vim-duzzle'

" Non github repos
NeoBundle 'git://git.wincent.com/command-t.git'
" Non git repos
NeoBundle 'http://svn.macports.org/repository/macports/contrib/mpvim/'

"-- Installation check.
NeoBundleCheck

"-------------------- Plugin settings --------------------
"--- Switch.vim
so ~/.vim/plugin/switch.vim

"--- neocomplete or neocomplcache
so ~/.vim/plugin/neocomplete.vim

"--- Syntastic
so ~/.vim/plugin/syntastic.vim

"--- Unite
so ~/.vim/plugin/unite.vim

"-- TextObject
so ~/.vim/plugin/textobject.vim

" quickrun
so ~/.vim/plugin/quickrun.vim

"--- vim-json
let g:vim_json_syntax_conceal = 1
let g:vim_json_syntax_concealcursor = 1

autocmd FileType json setlocal sw=2 sts=2 ts=2 et

"--- sass
let g:sass_compile_auto = 1
let g:sass_compile_cdloop = 5
let g:sass_compile_cssdir = ['css', 'stylesheet']
let g:sass_compile_file = ['scss', 'sass']
let g:sass_started_dirs = []

autocmd FileType less,sass setlocal sw=2 sts=2 ts=2 et

"--- Alignta
xnoremap al :Alignta<Space>

"--- vim-over
nnoremap <silent> <Leader>m :OverCommandLine<CR>%s/

"--- yankround
"" keymaps
nmap p <Plug>(yankround-p)
xmap p <Plug>(yankround-p)
nmap P <Plug>(yankround-P)
nmap gp <Plug>(yankround-gp)
xmap gp <Plug>(yankround-gp)
nmap gP <Plug>(yankround-gP)
nmap <C-p> <Plug>(yankround-prev)
nmap <C-n> <Plug>(yankround-next)

"--- AlpacaTags
let g:alpaca_tags#config = {
      \ '_' : '-R --sort=yes --languages=+Ruby --languages=-js,JavaScript',
      \ 'js' : '--languages=+js',
      \ '-js' : '--languages=-js,JavaScript',
      \ 'vim' : '--languages=+Vim,vim',
      \ 'php' : '--languages=+php',
      \ '-vim' : '--languages=-Vim,vim',
      \ '-style': '--languages=-css,scss,js,JavaScript,html',
      \ 'scss' : '--languages=+scss --languages=-css',
      \ 'css' : '--languages=+css',
      \ 'java' : '--languages=+java $JAVA_HOME/src',
      \ 'ruby': '--languages=+Ruby',
      \ 'coffee': '--languages=+coffee',
      \ '-coffee': '--languages=-coffee',
      \ 'bundle': '--languages=+Ruby',
      \ }

au FileType ruby,eruby setl tags+=~/.vim/tmp/rtags

"---------------------------------------------------------------------
"--- vim general settings
set ambiwidth=double
set backupdir=$HOME/.vim/tmp/
set backupskip=/tmp/*,/private/tmp/*
set directory=$HOME/.vim/tmp/
set viminfo+=n~/.vim/tmp/viminfo.txt
set browsedir=buffer
set nocompatible
set expandtab
set hidden
set incsearch
set list
set listchars=tab:>\ ,extends:<
set number
set showmatch
set smartcase
set whichwrap=b,s,h,l,<,>,[,]
set autochdir

syntax on
filetype on
filetype indent on
filetype plugin on
set t_Co=256
set enc=utf-8
set fenc=utf-8
set fencs=utf-8,iso-2022-jp,euc-jp,cp932
set fileformats=unix,mac,dos
set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P

" activate molokai colorscheme
colorscheme molokai

" change the leader key to the ";"
let mapleader = ";"
noremap \ ;

" copy to clipboard when yanked
set clipboard=unnamed

" 表示行単位で移動
nnoremap j gj
nnoremap k gk
nnoremap <Down> gj
nnoremap <Up>   gk

" <C-g> show the full file path
nnoremap <C-g> 1<C-g>

" tagsジャンプの時に複数ある時は一覧表示
nnoremap <C-]> g<C-]>

" Change color on status line when input mode
augroup InsertHook
autocmd!
autocmd InsertEnter * highlight StatusLine guifg=#ccdc90 guibg=#2E4340
autocmd InsertLeave * highlight StatusLine guifg=#2E4340 guibg=#ccdc90
augroup END

" Indent length
set autoindent
set smartindent
set smarttab
set tabstop=2
set shiftwidth=2
au BufNewFile,BufRead *\.md set tabstop=4 shiftwidth=4
au BufNewFile,BufRead *\.c set tabstop=4 shiftwidth=4
au BufNewFile,BufRead *\.cpp set tabstop=4 shiftwidth=4
au BufNewFile,BufRead *\.java set tabstop=4 shiftwidth=4
au BufNewFile,BufRead *\.h set tabstop=4 shiftwidth=4
au BufNewFile,BufRead *\.css set tabstop=4 shiftwidth=4
au BufNewFile,BufRead *\.scss set tabstop=4 shiftwidth=4
au BufNewFile,BufRead *\.gradle set tabstop=4 shiftwidth=4

" Python
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

" Json formatting
command! Jf :execute '%!python -mjson.tool'
  \ | :execute '%!python -c "import re,sys;chr=__builtins__.__dict__.get(\"unichr\", chr);sys.stdout.write(re.sub(r\"\\u[0-9a-f]{4}\", lambda x: chr(int(\"0x\" + x.group(0)[2:], 16)), sys.stdin.read()))"'
  \ | :%s/ \+$//ge
  \ | :set ft=javascript
  \ | :1

" Highlight the trailing whitespace
augroup HighlightTrailingSpaces
  autocmd!
  autocmd VimEnter,WinEnter,ColorScheme * highlight TrailingSpaces term=underline guibg=Red ctermbg=Red
  autocmd VimEnter,WinEnter * match TrailingSpaces /\s\+$/
augroup END
