# oh-my-zsh
source ~/.zsh/oh-my-zsh

# autoload
fpath+=~/.zsh/zfunc
autoload -U compinit
compinit

# setup environments
if [[ -z $TMUX ]]; then
    source ~/.zsh/env
fi

# aliases
source ~/.zsh/alias

# git-ignored
[ -f ~/.zsh/secret ] && source ~/.zsh/secret

# direnv hook
which direnv > /dev/null 2>&1 && eval "$(direnv hook zsh)"

# history
HISTFILE=~/.history-zsh
HISTSIZE=1000000
SAVEHIST=1000000
setopt APPEND_HISTORY
## for sharing history between zsh processes
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

# Disable Ctrl+S(terminal lock)
stty stop undef

# enable color
export CLICOLOR=1
autoload -U colors; colors

# prompt
PROMPT="
%{$fg_bold[blue]%}${HOST[0,7]} ${PROMPT}%{%(?.$fg[cyan].$fg[red])%}%(?.(▰╹◡╹%).ヾ(｡>﹏<｡%)ﾉ)%{$reset_color%}%b "
## continuation of command
PROMPT2='%B%_%(?.%f.%S%F)%b %#%f%s '
## auto correct
setopt correct
SPROMPT="%r is correct? [n,y,a,e]: "
