# oh-my-zsh
source ~/.zsh/oh-my-zsh

# command complement
autoload -U compinit
compinit

# Disable Ctrl+S(terminal lock)
stty stop undef

# rbenv
eval "$(rbenv init -)"

# added by travis gem
[ -f /Users/yusuke/.travis/travis.sh ] && source /Users/yusuke/.travis/travis.sh

# environments
source ~/.zsh/env
source ~/.zsh/options

# aliases
source ~/.zsh/alias

# git-ignored
source ~/.zsh/secret

# extensions
source ~/.zsh/functions
source ~/.zsh/peco

# oh-my-zsh
ZSH_THEME="powerline"
POWERLINE_HIDE_HOST_NAME="true"
POWERLINE_HIDE_GIT_PROMPT_STATUS="true"
POWERLINE_SHOW_GIT_ON_RIGHT="true"
