# oh-my-zsh
source ~/.zsh/oh-my-zsh

# command complement
autoload -U compinit
compinit

# Disable Ctrl+S(terminal lock)
stty stop undef

# rbenv
eval "$(rbenv init -)"

# added by travis gem
[ -f /Users/yusuke/.travis/travis.sh ] && source /Users/yusuke/.travis/travis.sh

# environments
source ~/.zsh/env
source ~/.zsh/options

# aliases
source ~/.zsh/alias

# extensions
source ~/.zsh/functions
source ~/.zsh/peco
