#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

# command complement
autoload -U compinit
compinit

# Disable Ctrl+S(terminal lock)
stty stop undef

# rbenv
eval "$(rbenv init -)"

# liquidprompt
source ~/dotfiles/liquidprompt/liquidprompt

# added by travis gem
[ -f /Users/yusuke/.travis/travis.sh ] && source /Users/yusuke/.travis/travis.sh

# environments
source ~/.zshrc_source/env
source ~/.zshrc_source/options

# aliases
source ~/.zshrc_source/alias

# extensions
source ~/.zshrc_source/functions
source ~/.zshrc_source/peco
